[build]
builder = "nixpacks"
buildCommand = "npm install --prefix api"

[deploy]
startCommand = "node api/src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
